#   Target
PROGRAM_spu := mbox_spu
LIBRARY_embed := lib_mbox_spu.a
CPPFLAGS_gcc := -Werror

# include partea care face toata treaba pe baza definitiilor de mai sus

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
